name: Setup environment
description: "Checkout project, set up Node and install dependencies"
inputs:
  cache_version:
    description: 'Value gets appended to the cache key and will therefore invalidate the cache if it changes'
    required: true
  platforms:
    description: 'x64 or arm64 platform'
    required: true
    default: x64

runs:
  using: "composite"
  steps:
    - name: Get current date
      shell: bash
      id: date
      run: echo "date=$(date +'calendar-week-%W')" >> $GITHUB_OUTPUT

    - name: Write cache version
      shell: bash
      working-directory: shared

      run: echo $CACHE_VERSION >> cache_version
      env:
        CACHE_VERSION: ${{ inputs.cache_version }}

    - name: Load cached venv
      id: cached-node-modules-dependencies
      uses: actions/cache@v3.0.11
      with:
        path: |
          ./shared/node_modules
          ./shared/package-lock.json
        # Cache the complete node_modules dir for a given os the current
        # calendar week and the cache version.
        # Providing a different value for the cache version enables manual
        # invalidation of the cache in case it is in some erroneous state.
        key: shared-node_modules-${{ runner.os }}-${{ hashFiles('./shared/package-lock.json') }}-${{ hashFiles('./shared/package.json') }}-${{ steps.date.outputs.date }}-${{ hashFiles('cache_version') }}

    - name: Remove cache version
      shell: bash
      working-directory: shared
      run: rm cache_version

    - name: Install dependencies
      if: ${{ steps.cached-node-modules-dependencies.outputs.cache-hit != 'true' && inputs.platform == 'x64' }}
      shell: bash
      working-directory: shared
      run: npm ci

    - name: Run the build process with Docker
      if: ${{ steps.cached-node-modules-dependencies.outputs.cache-hit != 'true' && inputs.platforms == 'arm64' }}
      uses: addnab/docker-run-action@v3
      with:
        image: arm64v8/node:18-alpine3.18
        options: |
          --volume ${{ runner.temp }}/shared:/shared
        run: |
          cd shared
          npm ci


