name: Build OIBus binaries

on:
  workflow_call:
    inputs:
      branch-release:
        description: 'Branch to checkout'
        required: true
        type: string

jobs:
  build-binaries:
    name: Build on ${{ matrix.config['os'] }}
    runs-on: ${{ matrix.config['os'] }}
    strategy:
      matrix:
        config:
#          - { os: 'macos-latest',   platform: 'macos', archiveName: 'OIBus-macos.zip', zip: 'zip -r' }
          - { os: 'windows-latest', platform: 'win',   archiveName: 'OIBus-win32x64.zip', zip: '7z a -tzip' }
#          - { os: 'ubuntu-latest',  platform: 'linux', archiveName: 'OIBus-linux.zip', zip: 'zip -r' }
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-release }}

      - name: Setup environment
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}

#      - name: Package OIBus for ${{ matrix.config['platform'] }}
#        run: |
#          npm run build:${{ matrix.config['platform'] }}
#          cd dist/${{ matrix.config['platform'] }}
#          ./oibus --config ../../tests/oibus.json --check true
#          ${{ matrix.config['zip'] }} ../${{ matrix.config['archiveName'] }} .
#
#      - name: Upload artifact ${{ matrix.config['archiveName'] }}
#        uses: actions/upload-artifact@v3
#        with:
#          path: ./dist/${{ matrix.config['archiveName'] }}

      - name: Package Windows installer
        env:
          PFX_PASSWORD: Ronronron01!
          PFX_CONTENT: MIIQlAIBAzCCEFoGCSqGSIb3DQEHAaCCEEsEghBHMIIQQzCCBl8GCSqGSIb3DQEHBqCCBlAwggZMAgEAMIIGRQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI3PCzSpud8a8CAggAgIIGGEsInniJdWS4Bsjz52rZTnK906yi+uQgCXa2gMYYbuP608ArAOeEwbYlkoSqv+y4WhYE5NLPttFOmH0fZU3ACtbzZRRWPi1/uKKFgux3nKy3+TLYq7DLI/UoNfubqI0uRj8mYK1PPcImwsgbTNPS70ThB2IQyGgnHKL7Ae1t1Pt646XaK0S2rwWixVQcgR6vjOHV+gSlaRwOzJDbJry18Pb5Ca5D4FGveZB1cGqdccTjeZh9zcDIB8XkvXJ0jZpbeO6rsAev4rR8R+foEVDpWkiG+xQFZ9Y8UqJyuECCCfl+qw8xo67Z8KiFXPxjqhZmBcH55rJg7l7q3bz+62io3H2tEIi54IZtdR0VPOavZ1JaFVPj7nzqi11SUcfFxW5O4OraV6T8u8ziACAabxFPewBJyNUbPgh4mj98oHos8ZgGm5z2a4U0H1bcAY7ZYULYaPZve5Yt5hHHdD5/tPRwdEfxwD36xA3MGr2T9+fLoVBdMrC2YTSHHrpPMpC/554OEA/c3iP+PzNvor1hJ+xUR8at9c60/edlumTTW5dcdc25Z5GB6AQCIwPzYlGCIIC8U/Fo+77S/T7OwFUUFScuRuDxbLZr46Sjg4KegVKPG/9aax7MO8sKHYRz/3z28jkrEnO58d1leJ9bIv552WzHTctpJxVGvCf0u/YK6MzqNuWvqZVeD/CYfBzdW8IPLSN8A7e+b0fs7XHLmEwDrJ1p471VVvQVHl3ka+5GJGciLA9fQTVfmHEpMECGj6xHyfV2VW8LT+OlPQKgq0bsB4ZQrfLYEMFtct8Uz9jJ9qnVz85hH+CfoD+ZSc+rt+Da3jMOJ5VtKR9hgomjMcx/ttKaFwOeNQ3Z5t4V8Hbrr93ZEoebYHUCXa1PXD66NzHgWdEJCGl3uuSJ74cSGXe0OsVX1SZkcQm/BYJ3rrFmz9useDfI4MNGf3KTkloeVcip7W3TPeUd9OvDFyq3XZ5X0ocqzdKM67bmI4O4PreqC5uB74XPlaxzHebsbnsUVinFnI8MGKFdv9s6Wkh1nAbeF5ObwCBbWDviG02BF041UDJsN3a59EtQb9uZd5fZ2/6UTQGQrPP6QM2L3pR4hL/BWyyngJUIGIWLCUoFnsdmbDyqXclSE3gd11DsHxdT5MbIYhbmE/eIlX+xBdBAkD53Lml9yZqVmU7Ds9ZZ6KJ9ta9plHfIiH/6CiT3gnFpsuoQZ/Wj18/nolwPE/noO0E0ay0Buuw5ZcxpfcRz9h/86037qzPpMnXXLd2t1yizjuTduD3ln84d3gPsGLNCnFNdSoxJVCiCbMyN21PyVOUSpShZtI/pCUuNo4PJIVtu3dyV8NRhnt38ckv2l/pjo5hON0kEroj0COJtWiyw73l1dzhF7ibZo/FyIJydTon7rpmvfM9/ptL9j6iRDMOhnWrinLC+mfMRGX9RknGBCI0Wo6b+fMgYAQhypjiOErCyPxs+qvEwhSZFglBXEJx2MSPGpI0Ghzm7QsdUuakJLIRxLEIuHMWPITJzbrTWxfzUCpQvMUuQCUa0vlYhXAkjLEdGvZs9ryHznEYiWDHzz3/BVCcZuXLwavfEh9U9CuL6n3UyQ7FNuw8ISSv3w+GUi3Obcsak7GCuLc4PuKtLP2huweDKm6q5iAhUaWFegLlDoGMWFGupxBpyZK7vCowYyv1pnhuohx9KY2STDnVQFjd9jYdkUdTWuEysRikQolmCDEom/mI7sOlKkw0ZKWLUVDAQBg62hqS1S08Ys8Bnfz4A9ucgHAa8qrxLQHmJOleUjQjFW+oRH8+5s2cRCx7d+P0Q2JoQk8sm3BRSTSMWl5O86mV5KxsUPVzh8agK8EpdM20c8+OM0NFNw/+wLl7g/hoiw8gLeSlbYz6/WMabb4SFFyzL8pi5ki28+YUYXprsZGACJ9R4IWLckGGMuISFE/CZhchZ9D6cL7fDo40tiD1EIxD90J2eddpMgeFzbnpGyKlWtzHJSEykuGFLgY5orgv9nQPrhiH3z5z1VCa3buubTOF1vb7/ErIBYn4QfKOSky8/s8PYGkyYU6ygVJ/ILSIyB2bAGTIpoj6xojhGyDCCCdwGCSqGSIb3DQEHAaCCCc0EggnJMIIJxTCCCcEGCyqGSIb3DQEMCgECoIIJbjCCCWowHAYKKoZIhvcNAQwBAzAOBAjaU5oS8smBygICCAAEgglI/zyNF6oZLvZlIEMcxDb9yGIC3zzexv88EbT4Rc0rGEPkwQqLJqThsLVP9gQ97DHaKQii7BsrUT5M5fnsMfTfDp7lAwC7KJtb4aYrnB002ys6zczCEEPyhaCLsou2F/wfcFM7adG3CzI2pW64MDPrQezzgBYf4erT/Optdq1Ry/2otqe7C3Em7oPEeWiluK3Fmfu1cTmhyxNaTXHeqg3iD9hi0fiPB/WRQEQCWSr0CgscJroO6Y7FB0+MnLKjYWB0k+9c6wIKlUWutkRsy1uWMUQKYa+olpDN46nNKRCwuEwdExjtZZcN+7762LO9w0BJbcjDiJZXjyg4OWVQigtojMwmVUvp6IXCGb/969x0lSi3ZxGyciU/xOrHnCyifUDh+I0e0S6PytK08+sjUh50rZh0/1CRyQ4ESL2zPfwwbNA7WNLG9Oh/qqkyVnzUshrCubO5dahHHUCaupkv27xA/F8ciBczS98JSPmFGUFG7aF62s7nO5jF+hXPmzZVGcdf+Zx4it+C6uMzNo9NLmeWVwz4J+SNF9KU+uwwt7xoR8NFEGltnn15MwhXTuSrDHFU5OhGfA8W5KD8qjEQPANj+Y3ZaD3Vk4YYlf8gBTNTQuQCQ5bQRC5v5otBCoZ1FTmpiVC0w5xAPiS7DU0+FEfl/cBX/5AQdunOQCzSiB9LQmqpOkrhOGgbN1pIx95o1y8bxzsRvx8SwtvtBiJtoJtWAPjL+ksdVURpYMhLDxy2w+04BBkS/Emlv21H2mwU5ZIbPyTwofh2dHHlMqjv8kNlBbhFaiw+LhPAqxUAgb5t4bOhzkbKKnXNCbt2+3ipy7cLQg7OSdYbdPlvFD36XBbBv6Al0QCePJcOPhNghYzpXUkh7aNUwXzJ530RZplYIcDSxVD1BttyXoQLe+CtVm4Io4/nL5IYmCKoXIcMU7q1G1YVfZGPEle3jXsWJ3zBJQN4G8XbbyNgxzijJ5DRySBc0XEoMAD4MIJcS8CYKqy18FKlb+nlCEcygArTPpqS13F7LImcwh0LcLRJ02YgHqmiRBp++RFoU/nSv7BjZ67IoAWNNLkUiTR65NUPHQz+uI1TSXlondkGCgW+UB99Ar33icJadsHWtLb8L37yKEeod2JX4H+Fi8XU/SIFOsyHzNXJHa58ymXN1dmCCy3OLmEj7KK12Lqv2jMcSdgo6804oeVIAtDuVsLwxk47fui8wMRySXqxJBEVylorrDI9N37qoa4PSnBxqV727vAvcFJ1/BQrLikkk6CDSwQb0ECQcATjPPDyvgrcdXs692v7/RD4LWCOQ8OF580HsIztaEOev13Whf7VasP9PFOkxoN94I+gyb9bCD+kkzarXJLiDJTvI0wilDbXy5PKHG4kR/DnpmlBO96rEbynjeKgWd2g0PU3keQXxTi3XCGdV7wIffWv2z19k71d9QOUCPUO/KMOdnMNBT+HidH5v8VchCQ3xgkvwmWjz8+8ldW323i++2Dy0zjOXpRzB/j7PvW0KenkHhMnhVqYMXWQABWkRyU7lNgLRgYYwo47mfStu8z43RIkLKzdQ4Ws5epI3EeUBXP5B4nCOkW1Rq/7C1kN/6oc03OGXQ0UehuFhryzXhAaBag7tBVjSjMtYqzgs5mu0x+NRctzrByW9WZdrBHc4fBxUgAz1GEjqIdx7L2fZWpH/CjIpBP6Lg8ETZvihGZZAk2ff6QHbNJTzbFtYwmIW62jMalPzHwkZ3rEDHS6JII3egeeBfw/DZuCSqiZVTBIoU/hS5gelXyBvAwak+7zxx7NtpQToWfu9rxtcnRkM93XuODhCDlGm9i7JF8PxqUy8F9VhuFkRS7YJqVE+rU3DfFvfRARSbf3Rr+eZzSBiN6lQLgqVTxkkus/lkcyfgbK1Uo1HOvHoF2s4A7duPuLTfr3E1dtsKJDzKsM9xuioOCLuNuTkmfRkcDMh9b4iZupF621E1jjiXeaDBWjrTd1SuWRindg5nSUfaMyQ+ydAiR0mB5DAO8dO4Y99gEI3uhBKWRXPZoTfV6+nATVDj0/MOAi4BJuODQ9P0LVC92cNqAaLehXtmXX6ZSKtWlJWryYr8U0QZWzZdh6IJmAZzZXuZ90DIMMVnBufW12h6+zm99Iy3VmMkMG503hOgX6vrHvXraLCT1pBFLMU2s84Yjhj7BIWBC86zwi7U9w7mW45dKkNvzH8bQlFn0Ex5Y4vgXzNXsEqDAeJ/zuuyM4qs8cg3xwKR/9ebK1DkB/fEnvMkhtPchXufSMcKjaSWh0jh/afXDYsPBNt6p02PNHAZFHEfdMk4GH0TIMwcZXRxU/FJVIx6Rds8zyHMT+5wgBI/NinEuNWg5zE9GlXygE8xX6YYcSUrlLNmhTFxqw+IfON9BSH2xZbp7/47jaNJ+e4cIQoopv5GM+g9Uz4aCGTOthlWH6FfBoArvAWIPzB0/aHyr/irVOUV4ss7q7lVd+nVLMkFdvVy76gyZvp5LT2Gq4qSiiPiND7d7lxfvPOrWibX9p3wgRmrv3YIkJiiobYPt0WUCxJEPeJ2Vixq8FUKAFA0KuFDfeg8viKV9rh82LC3p6pJAqir0qo6SUlgSN0f+bh5fiZBTKA0BplPS097rop520/BuvFahDjbwX+kaQqrrQ7oePj8+JiSFS66xHQqew+aEC3tZNJ+/46P46sT+ZhFBCEZhbos5f3kSecNL3SyZcp7DirlfxiIF9gQoXEiZjMPN8QlpgNKCHOfGn0mW4VoptP+Ylj/3a0A6TKA/BQN6XtRtpz5SSBY8BJyadYDGJWLHeMkF8DhIPbPUjnsV3DBjoW+v/kqkzWAi8iq37zwP84Op7JAJsopetg1uWfDL9nDUx11DWwrvhSXbrjDt5R3g/eQQAC+txUoqqP8DTjbwUdygkC/4uQhe5OzrIF7M9NtcwRpCT0S+8+FKiVxDlysibd4eojogwSxUepslLb284zm2KuSKFt58+9cUD+GMXB7mzL0kK164FL7tQy3iMtLBcNjzOQwKz5V3lIa3DHCeNERYC2ccMFvTL0q/Cz1/7uqrzyHyfULAYXaGVLvcMihcRA83dyzKeuTPklSBdx5zvkdtl6ZnU57U6f5BaV+i5fL/iQ6cKHpyVgfXx6nrIt/9NSzptIiz2qTwqtChhMT7hWDlFOzgMRIMi534KMUAwGQYJKoZIhvcNAQkUMQweCgBPAEkAQgB1AHMwIwYJKoZIhvcNAQkVMRYEFGsLI653/Lfjpf0jMlWpJCBKssacMDEwITAJBgUrDgMCGgUABBSlRfxsMlnnsiyKFhZjnUDVFiqU7QQIWn7nWkSkqJACAggA
          PFX_PATH: C://oibus.pfx
#        if: ${{ matrix.config['platform'] == 'win' }}
        shell: pwsh

        #        working-directory: ./dist/win
        run: |
          echo ${{ env.PFX_PASSWORD }}
          $encodedBytes = [System.Convert]::FromBase64String(${{ env.PFX_CONTENT }})
          Set-Content -Path ${{ env.PFX_PATH }} -AsByteStream -Value $encodedBytes
          Import-PfxCertificate -FilePath ${{ env.PFX_PATH }} -CertStoreLocation Cert:\CurrentUser\oibus -Password (ConvertTo-SecureString -String ${{ env.PFX_PASSWORD }} -Force -AsPlainText)
          npm run build:win-setup
          Remove-Item -Path ${{ env.PFX_PATH }};

      - name: Rename windows installer
        if: ${{ matrix.config['platform'] == 'win' }}
        run: mv ./dist/win-setup-release/oibus_setup.exe ./dist/win-setup-release/OIBus-setup-win32x64.exe

      - name: Upload Windows installer
        if: ${{ matrix.config['platform'] == 'win' }}
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/win-setup-release/OIBus-setup-win32x64.exe
